import { useState, useEffect, useRef } from 'react'
import Collapse from '@material-ui/core/Collapse'
import Fade from '@material-ui/core/Fade'
import Slide from '@material-ui/core/Slide'
import Paper from '@material-ui/core/Paper'
import { PostInterface } from '@/interfaces/Strapi'
import Box from '@material-ui/core/Box'
import { makeStyles } from '@material-ui/core/styles'
import Typography from '@material-ui/core/Typography'
